### ISSUE TITLE
Wait for website to load

### ISSUE THREAD

**Issue by Souroba** [lankybutmacho/web-to-kindle-heroku#1]
Is it possible to add another variable in your tool, to add a time to wait for a google calendar to load, before creating the image?

**Comment by lankybutmacho** [comment]
Yeah, that'd be possible - Puppeteer has a couple methods for waiting until a page has loaded. You'd want to add a line before `await page.screenshot({` that's something like `page.waitForTimeout(1000)`. Or for a more robust solution you could use `page.waitForSelector()` instead and pass it a selector for an element you're expecting to be on the page once it's done loading. Here are the docs for those two methods:

https://pptr.dev/api/puppeteer.page.waitfortimeout
https://pptr.dev/api/puppeteer.page.waitforselector

**Comment by adelriop** [comment]
Hi! I have the same issue. I used your great idea to show some info of a solar energy system in a remote home in the mountains, but sometimes the screenshot is too fast and the solar system info (emoncms) is not fully loaded yet. If you ever plan on updating the code and adding the "delay" variable as Souroba suggested, it would be awesome for those with no programming skills that still managed to follow your great tutorial. Thanks a lot!
